<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="16" passed="13">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4256" started-at="2015-05-18T20:46:51Z" finished-at="2015-05-18T20:46:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4256" started-at="2015-05-18T20:46:51Z" finished-at="2015-05-18T20:46:55Z">
      <class name="com.FCI.SWE.ServicesModels.UserServicesTest">
        <test-method status="FAIL" signature="PageService()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="PageService" duration-ms="2998" started-at="2015-05-18T23:46:51Z" finished-at="2015-05-18T23:46:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [{"status":" accept"}] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [{"status":" accept"}] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.FCI.SWE.ServicesModels.UserServicesTest.PageService(UserServicesTest.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:352)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:347)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PageService -->
        <test-method status="FAIL" signature="TimelinePostService()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="TimelinePostService" duration-ms="49" started-at="2015-05-18T23:46:54Z" finished-at="2015-05-18T23:46:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [{"status":" accept"}] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [{"status":" accept"}] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.FCI.SWE.ServicesModels.UserServicesTest.TimelinePostService(UserServicesTest.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:352)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:347)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TimelinePostService -->
        <test-method status="FAIL" signature="acceptrequestService()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="acceptrequestService" duration-ms="58" started-at="2015-05-18T23:46:54Z" finished-at="2015-05-18T23:46:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [{"status":" accept"}] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [{"status":" accept"}] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.FCI.SWE.ServicesModels.UserServicesTest.acceptrequestService(UserServicesTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:352)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:347)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- acceptrequestService -->
        <test-method status="PASS" signature="activepageservice()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="activepageservice" duration-ms="672" started-at="2015-05-18T23:46:54Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- activepageservice -->
        <test-method status="PASS" signature="chat()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="chat" duration-ms="28" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- chat -->
        <test-method status="PASS" signature="create_pageService()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="create_pageService" duration-ms="118" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_pageService -->
        <test-method status="PASS" signature="hashservice()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="hashservice" duration-ms="46" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hashservice -->
        <test-method status="PASS" signature="loginService()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="loginService" duration-ms="24" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginService -->
        <test-method status="PASS" signature="postservice()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="postservice" duration-ms="14" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postservice -->
        <test-method status="PASS" signature="registrationService()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="registrationService" duration-ms="56" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registrationService -->
        <test-method status="PASS" signature="searchService()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="searchService" duration-ms="23" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchService -->
        <test-method status="PASS" signature="seenservicee()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="seenservicee" duration-ms="31" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- seenservicee -->
        <test-method status="PASS" signature="sendgroup()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="sendgroup" duration-ms="26" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendgroup -->
        <test-method status="PASS" signature="sendmsgService()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="sendmsgService" duration-ms="15" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendmsgService -->
        <test-method status="PASS" signature="sendrequestService()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="sendrequestService" duration-ms="23" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendrequestService -->
        <test-method status="PASS" signature="signoutService()[pri:0, instance:com.FCI.SWE.ServicesModels.UserServicesTest@22b3cbc0]" name="signoutService" duration-ms="15" started-at="2015-05-18T23:46:55Z" finished-at="2015-05-18T23:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signoutService -->
      </class> <!-- com.FCI.SWE.ServicesModels.UserServicesTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
